run:
  skip-dirs-use-default: true # include `vendor` `third_party` `testdata` `examples` `Godeps` `builtin`
  skip-dirs:
    - conf
    - mock
    - test
    - tests
    - clients
    - pb_gen
    - rpc_gen
    - thrift_gen
  skip-files:
    - ".*\\.generated\\.go$"
    - ".*\\.gen\\.go$"
    - ".*\\.mock\\.go$"
    - ".*\\.thrift\\.go$"

linters:
  disable-all: true # disable all linters, but left linters below
  enable:
    - bodyclose     # checks whether HTTP response body is closed successfully
    - errcheck      # checking for unchecked errors in go programs
    - staticcheck   # go vet on steroids, applying a ton of static analysis checks
#    - unused        # checks Go code for unused constants, variables, functions and types
    - varcheck      # finds unused global variables and constants
    - structcheck   # finds unused struct fields
    - deadcode      # finds unused code
    - unparam       # finds unused function parameters
    - goconst       # finds repeated strings that could be replaced by a constant
    - govet         # examines Go source code and reports suspicious constructs
    - gofmt         # checks whether code was gofmt-ed
    - goimports     # does everything that gofmt does, additionally it checks unused imports
    - gosimple      # for Go source code that specializes in simplifying a code
    - ineffassign   # detects when assignments to existing variables are not used
    - typecheck     # parses and type-checks Go code
    - dogsled       # for Go source code that specializes in simplifying a code
    - exportloopref # checks for pointers to enclosing loop variables
    - misspell      # finds commonly misspelled English words in comments

issues:
  exclude-use-default: true
